export interface ChangelogEntry {
  version: string;
  date: string;
  tags: ("feature" | "fix" | "improvement" | "breaking")[];
  title: string;
  changes: string[];
}

export const changelog: ChangelogEntry[] = [
  {
    version: "1.2.0",
    date: "2026-04-08",
    tags: ["fix"],
    title: "Bugfix-Runde: Route-Mismatches & fehlende Endpunkte",
    changes: [
      "Dashboard-API hinzugefügt: Stats, nächste Events und Aktivität werden jetzt korrekt geladen",
      "Scouting: API-Routen und Datenmodell an Server angepasst (Opponent-Modell mit Bedrohungsstufen)",
      "Scrims-Ergebnis: HTTP-Methode korrigiert (PATCH → POST)",
      "Ankündigungen Pin/Bestätigen: HTTP-Methode korrigiert (PATCH → POST)",
      "Attendance-Abstimmung: Route korrigiert (/token/vote → /token)",
      "Verfügbarkeit: Tab-Buttons werden jetzt korrekt gestylt (primary statt ungültiges default)",
      "Lineup: Nicht-existierendes Aktivieren-Feature entfernt",
      "MOSS-Standalone-Seite leitet auf Matches weiter (MOSS ist jetzt pro Match)",
      "Server: Mitglied-Entfernen-Endpunkt hinzugefügt (DELETE /api/team/members)",
      "Server: Team-Logo-Upload-Endpunkt hinzugefügt (POST /api/team/logo)",
      "Letzte Umlaute korrigiert (Aktivitaet → Aktivität)",
    ],
  },
  {
    version: "1.1.0",
    date: "2026-04-08",
    tags: ["feature", "fix", "improvement"],
    title: "Match-Detail, externe Spieler & UI-Überarbeitung",
    changes: [
      "Match-Detail-Seite mit Spieler-Stats, MOSS-Uploads und Replays pro Match",
      "Externe/Aushilfsspieler können zu Matches hinzugefügt werden",
      "MOSS-Dateien werden pro Match und pro Spieler zugeordnet",
      "Replays sind jetzt direkt im Match verknüpft statt als eigener Bereich",
      "Training: Treffzeit (Pflicht), Beginn (Pflicht) und Ende (optional) hinzugefügt",
      "Scrims: Optionale Treffzeit hinzugefügt",
      "Match-Ergebnis wird automatisch aus den Scores berechnet (WIN/LOSS/DRAW)",
      "Maps werden aus der R6 Siege Game-Config geladen statt hardcoded",
      "Einstellungen nur noch für Admins sichtbar und zugänglich",
      "Sidebar zeigt Einstellungen nur für Admins",
      "MOSS und Replays aus der Navigation entfernt (jetzt unter Matches)",
      "Alle deutschen Texte verwenden echte Umlaute (ä, ö, ü) statt ae, oe, ue",
      "Changelog ist jetzt einklappbar, nur neueste Version aufgeklappt",
      "Fix: /api/teams → /api/team (404 nach Login behoben)",
      "Fix: /api/members → /api/team/members (Mitgliederliste war leer)",
      "Fix: Cookie secure-Flag basiert auf APP_URL statt NODE_ENV",
      "Fix: Root-Seite (/) leitet korrekt zum Dashboard weiter",
      "Fix: Favicon und Login-Logo zeigen die echten Team-Bilder",
      "Fix: Discord-Icon auf Login-Seite hat jetzt die Augen",
      "Fix: Admin-Zugriff nur noch über .env (ADMIN_USER_IDS/ADMIN_ROLE_IDS), nicht mehr erster User",
      "GitHub-Repository umgezogen nach NKr-NextDestiny/NextPhantomsHQ",
    ],
  },
  {
    version: "1.0.0",
    date: "2026-04-08",
    tags: ["feature"],
    title: "Umbenennung & Feature-Komplettpaket",
    changes: [
      "Projekt umbenannt von NextPhantoms zu Next Phantoms HQ",
      "Wiki für Team-Wissensdatenbank",
      "Persönliche und Team-Notizen mit Privat-Modus",
      "Erinnerungen und Deadlines mit Überfällig-Anzeige",
      "Verfügbarkeits-Heatmap für das ganze Team",
      "Training-Vorlagen für schnelles Erstellen",
      "Match-Reviews mit Positives/Negatives/Verbesserungen",
      "Globale Suche über alle Bereiche",
      "Discord-Webhooks für Match-, Training- und Scrim-Benachrichtigungen",
      "Benutzer-Dokumentation mit allen Features erklärt",
      "Changelog-Seite mit Versionsverlauf",
      "Alle Dependencies auf neueste stabile Versionen aktualisiert",
      "dev.bat: Automatischer Browser-Start, server/.env Auto-Erstellung",
      "clean.bat: Menü mit Optionen (nur Daten / alles / abbrechen)",
    ],
  },
  {
    version: "0.3.0",
    date: "2026-04-07",
    tags: ["feature", "fix"],
    title: "Lokale Entwicklung & DB-Fix",
    changes: [
      "server/.env für lokale Prisma-Migration mit localhost-URL",
      "prisma.config.ts liest DATABASE_URL manuell (Prisma 7 Kompatibilität)",
      "Fix: Server-Crash 'Can't reach database server at postgres' im lokalen Dev",
      "Fix: config/index.ts lädt server/.env vor root .env (localhost hat Priorität)",
    ],
  },
  {
    version: "0.2.0",
    date: "2026-04-07",
    tags: ["feature"],
    title: "R6 Siege Replay-Parser",
    changes: [
      "R6 Siege .rec Replay-Parser mit ZIP-Extraktion",
      "Kill-Erkennung und Runden-Statistiken aus Replay-Dateien",
      "Automatisches Parsen im Hintergrund nach Upload",
      "Spieler-Zuordnung per R6-Username",
      "ADMIN_USER_IDS für benutzerbasierte Admin-Zuweisung über Discord-ID",
    ],
  },
  {
    version: "0.1.0",
    date: "2026-04-06",
    tags: ["feature"],
    title: "Initial Release",
    changes: [
      "Discord OAuth Login mit Guild-Mitgliedschaft und Rollen-Prüfung",
      "Training-Verwaltung mit Abstimmungen und Erinnerungen",
      "Scrim-Management mit Ergebnissen und Bewertungen",
      "Match-Tracking mit Spieler-Statistiken",
      "Strategien-System mit Versionierung und Playbooks",
      "Lineup-Builder für Map/Side-Kombinationen",
      "Gegner-Scouting mit Bedrohungslevel und Notizen",
      "MOSS-Dateien Upload und Verwaltung",
      "Umfragen mit Mehrfachauswahl und Ablaufdatum",
      "Ankündigungen mit Pin-Funktion",
      "AES-256-GCM Dateiverschlüsselung für alle Uploads",
      "E-Mail-Benachrichtigungen via SMTP",
      "Echtzeit-Updates via Socket.io",
      "Responsive Dark-Theme mit Orange-Akzent",
      "JWT-Authentifizierung mit httpOnly Cookies",
      "PostgreSQL mit Prisma 7 ORM",
    ],
  },
];
