export interface ChangelogEntry {
  version: string;
  date: string;
  tags: ("feature" | "fix" | "improvement" | "breaking")[];
  title: string;
  changes: string[];
}

export const changelog: ChangelogEntry[] = [
  {
    version: "2.4.5",
    date: "2026-04-25",
    tags: ["fix", "improvement"],
    title: "Aktivitätslog, WhatsApp-Demos und stabilere Gruppen-Automation",
    changes: [
      "Zusatzblöcke für die WhatsApp-Gruppenbeschreibung lassen sich jetzt direkt in den Einstellungen bearbeiten statt nur löschen",
      "WhatsApp-Aktionen wie Befehlsliste posten oder Gruppenbeschreibung aktualisieren haben jetzt Cooldowns mit sichtbarem Countdown, damit nichts zugespammt wird",
      "Admin-Oberfläche für WhatsApp und Spielkonfiguration weiter enthardcoded und sprachlich bereinigt",
      "Bot-Befehle, Gruppenbeschreibung und Standard-WhatsApp-Nachrichten nutzen jetzt wieder korrekte Umlaute und passendere Emojis",
      "Übersetzungen werden clientseitig robuster gegen alte Zeichenkodierungsfehler bereinigt, damit kaputte Texte nicht mehr als Mojibake auftauchen",
      "Dashboard zeigt bei Aktivitäten jetzt nur noch die neuesten Einträge und verlinkt in ein eigenes Aktivitätslog mit Team-/Admin-Sicht",
      "Aktivitätslog-Einträge werden serverseitig in Klartext aufbereitet, damit keine internen Schlüssel wie dashboard.entities.whatsapp_command_post mehr auftauchen",
      "Umfragen speichern jetzt wieder korrekt; Poll-Frontend und Poll-API sprechen wieder dasselbe Datenformat",
      "Reminder speichern wieder korrekt und neue Reminder/Umfragen werden nun ebenfalls in die WhatsApp-Gruppe gespiegelt",
      "WhatsApp-Settings können jetzt Demo-Nachrichten für Ankündigungen, Match-Ergebnisse und Umfrage-Ergebnisse direkt in die Gruppe schicken",
      "Evolution-Webhook ist robuster und akzeptiert jetzt sowohl Root-Webhooks als auch /messages-upsert für Bot-Befehle",
      "Angepinnter WhatsApp-Befehlspost ist besser formatiert und lässt sich im Vollbild bearbeiten; Speichern schwebt jetzt unten rechts",
    ],
  },
  {
    version: "2.4.3",
    date: "2026-04-25",
    tags: ["fix", "improvement"],
    title: "Browser-Benachrichtigungen folgen jetzt dem Browser selbst",
    changes: [
      "Browser-Benachrichtigungen fragen jetzt beim ersten App-Start direkt ueber den nativen Browser-Prompt an, statt ueber einen zusaetzlichen In-App-Schalter simuliert zu werden",
      "Kuenstliche Notification-Toggles aus Header und Einstellungen entfernt; danach gilt nur noch die echte Browser-Berechtigung",
      "WhatsApp-Befehlsliste in den Settings zeigt jetzt auch die Varianten mit Umlauten wie !nächstes und !ankündigungen",
      "README bei der Evolution-Einrichtung um eine klarere Anleitung zur WhatsApp-Gruppen-ID ergaenzt, inklusive Hinweis auf das @g.us-Format",
    ],
  },
  {
    version: "2.4.2",
    date: "2026-04-25",
    tags: ["improvement", "breaking"],
    title: "Evolution Manager als einzige Setup-Oberflaeche",
    changes: [
      "In-App-Werkzeuge fuer Instanz-Erstellung, QR-/Pairing-Code, Gruppenabruf und Webhook-Setup entfernt, damit Evolution-Setup nur noch an einer Stelle stattfindet",
      "WhatsApp-Einstellungen im Projekt auf die wirklich benoetigten App-Daten reduziert: globale Schalter, Gruppen-JID und Versandmodi",
      "Server-Routen und Hilfsskripte fuer Evolution-Manager-Aufgaben entfernt, die jetzt ausschliesslich ueber den Evolution Manager erledigt werden",
      "README neu geordnet: erst Evolution API und Manager aufsetzen, dann Webhook im Manager setzen, danach erst Next Phantoms HQ verbinden",
    ],
  },
  {
    version: "2.4.1",
    date: "2026-04-25",
    tags: ["fix", "improvement"],
    title: "QR-Code-Fix und Dependency-Haertung",
    changes: [
      "QR-Code-Anzeige in den Evolution-Adminwerkzeugen repariert: das Frontend verwendet jetzt die erzeugte Data-URL korrekt statt sie doppelt zu kodieren",
      "Workspace-Dependencies auf aktuelle sichere Patch-Staende angehoben, darunter Next.js, React, Prisma, Tailwind, TypeScript, Vitest und Nodemailer",
      "Transitive Sicherheits-Overrides fuer PostCSS und @hono/node-server hinterlegt, damit die bekannten Advisories nicht ueber indirekte Abhaengigkeiten wieder hereinkommen",
    ],
  },
  {
    version: "2.4.0",
    date: "2026-04-23",
    tags: ["feature", "improvement", "breaking"],
    title: "Evolution Admin-Werkzeuge, Gruppenbeschreibung & WhatsApp-Befehle",
    changes: [
      "Alle Altlasten des frueheren WhatsApp-Providers aus dem aktiven Projekt entfernt; frische Evolution-API-Ausrichtung fuer Neuinstallationen",
      "Admin-UI fuer Evolution API erweitert: Instanz erstellen, QR/Pairing-Code holen, Webhook setzen und WhatsApp-Gruppen-IDs abrufen",
      "Automatische WhatsApp-Gruppenbeschreibung eingebaut: naechster Termin, Abstimmungsstatus, offene Umfragen, Folgetermine und eigene Zusatzbloecke",
      "Neue WhatsApp-Befehle fuer Gruppen: !hilfe, !befehle, !naechstes, !termine, !umfragen, !ankuendigungen und !status",
      "Bot-Befehle akzeptieren jetzt sowohl Schreibweisen mit Umlauten als auch ae/oe/ue-Varianten, also z.B. !nächstes und !naechstes",
      "Admin kann die fertige Befehlsliste direkt in die WhatsApp-Gruppe posten, damit sie angepinnt werden kann",
      "E-Mail-Erinnerungen zeigen bei bereits vorhandener Abstimmung jetzt direkt den bestehenden Status statt einen zweiten Aenderungsweg",
      "CLI-Helfer hinzugefuegt, um Gruppen-IDs auch direkt auf dem Server ueber Evolution API auszulesen",
      "README fuer Setup, Evolution-Adminfunktionen, Gruppenbeschreibung und Bot-Befehle aktualisiert",
    ],
  },
  {
    version: "2.3.0",
    date: "2026-04-23",
    tags: ["feature", "improvement", "breaking"],
    title: "Evolution API, Docker-First Betrieb & Admin-gesteuerte Benachrichtigungen",
    changes: [
      "WhatsApp komplett auf Evolution API umgestellt",
      "Ankündigungen, Match-Ergebnisse und Poll-Ergebnisse können per WhatsApp als Text, Bild oder Bild+Text verschickt werden",
      "Allgemeine WhatsApp-Nachrichten werden an eine konfigurierbare Gruppe gesendet; Abstimmungs-Links gehen privat an einzelne Spieler",
      "E-Mail ist global aktivierbar und pro Spieler durch Admins zusätzlich ein- oder ausschaltbar",
      "WhatsApp ist global aktivierbar; private Reminder nutzen die beim Spieler hinterlegte Telefonnummer",
      "Attendance-Links per E-Mail sind nach einer Antwort read-only; private WhatsApp-Links erlauben Updates innerhalb eines 5-Minuten-Fensters",
      "Jede externe Nachricht enthält jetzt einen klaren Hinweis, dass sie automatisiert erzeugt wurde",
      "Replay-Parser gegen echte Rainbow-Six-Replays nachgeschärft: bessere Spielererkennung, alle zstd-Frames werden ausgewertet",
      "Docker-First Betrieb vereinheitlicht: Development unter Windows und Updates laufen jetzt über Docker Compose",
      "Dokumentation für App-Deployment und separate Evolution-API-VM auf Debian 13 vollständig überarbeitet",
    ],
  },
  {
    version: "2.2.0",
    date: "2026-04-09",
    tags: ["feature", "fix"],
    title: "Match-Modus, Training-Verknüpfung & CSRF-Fix",
    changes: [
      "Matches: Zwei Modi beim Erstellen — 'Geplant' (mit Treffzeit, Abstimmung, Kontakt, Region) und 'Nachträglich' (mit optionaler Training-Verknüpfung)",
      "Matches: Nachträgliche Matches können mit einem bestehenden Training verknüpft werden (Dropdown im Formular)",
      "Fix: Speichern funktioniert wieder — CSRF-Token wird jetzt korrekt zwischen Client und Server ausgetauscht (behebt 'Fehler beim Speichern' auf allen Seiten)",
      "Fix: CSRF-Cookie von 'strict' auf 'lax' geändert für bessere Kompatibilität mit Cross-Origin-Setups",
      "Fix: Auth — Admin-User müssen jetzt auch auf dem Discord-Server sein (kein Guild-Bypass mehr)",
    ],
  },
  {
    version: "2.1.0",
    date: "2026-04-09",
    tags: ["feature", "improvement", "fix"],
    title: "Alle API-Features im UI, Suche, Statistiken & Export",
    changes: [
      "Globale Suche im Header — durchsucht Trainings, Matches, Strategien, Wiki und Spieler in Echtzeit",
      "Match-Statistiken: Detaillierte Auswertung pro Map und pro Gegner (Winrate, Runden, W/L) per Klick aufrufbar",
      "Admin-Dashboard: Erweiterte Statistiken mit User-Aktivität (7 Tage), Entity-Counts, API-Requests (30 Tage) und Speicherverbrauch",
      "Game Config in Einstellungen: Maps, Operatoren, Character-Label und Spieler-Rollen direkt im UI bearbeitbar",
      "Daten-Export: Match-Statistiken, Training-Teilnahme und Verfügbarkeit als CSV oder JSON exportierbar (unter Team-Einstellungen)",
      "Kommentar-System: Kommentare unter Match-Reviews schreiben, lesen und löschen",
      "Strategie-Favoriten: Strats mit Stern als Favorit markieren/entmarkieren",
      "Training-Vorlagen verwalten: Vorlagen-Manager zum Ansehen und Löschen von gespeicherten Vorlagen",
      "Stimme zurückziehen: Bei Trainings, Matches und Umfragen kann die eigene Stimme durch erneutes Klicken zurückgezogen werden",
      "Attendance-Token-Seite: Vote-Werte korrigiert (uppercase AVAILABLE/UNAVAILABLE/MAYBE) und Response-Mapping repariert",
      "Admin-Rolle nicht mehr über UI setzbar — Admin wird ausschließlich über Discord-Rollen (ADMIN_ROLE_IDS) und .env (ADMIN_USER_IDS) vergeben",
      "Mitglieder-Dropdown: ADMIN aus der Rollen-Auswahl entfernt (nur TRYOUT bis CAPTAIN wählbar)",
    ],
  },
  {
    version: "2.0.0",
    date: "2026-04-09",
    tags: ["feature", "improvement", "fix"],
    title: "Profil-Dropdown, Tab-Persistenz & UX-Verbesserungen",
    changes: [
      "Persönliche Einstellungen (Name, E-Mail, Telefon, Sprache, Browser-Notifications) jetzt im Profil-Dropdown oben rechts — für alle Benutzer zugänglich",
      "Einstellungen-Seite ist jetzt rein Admin-only (kein persönlicher Tab mehr)",
      "Tab-Persistenz: Aktiver Tab bleibt nach Reload erhalten (Einstellungen, Verfügbarkeit, Match-Detail) — URL-Parameter ?tab=...",
      "Ungespeicherte Änderungen: Warnung beim Verlassen wenn Formularfelder geändert aber nicht gespeichert wurden",
      "Mitglieder-Verwaltung: Rolle und Status direkt per Dropdown änderbar (TRYOUT bis ADMIN, ACTIVE/SUBSTITUTE/BENCH/INACTIVE)",
      "Mitglieder-Badges: Kein doppeltes Admin-Badge mehr",
      "Standard-Team: Name 'Next Phantoms' und Tag 'nD' statt 'Next Phantoms HQ' / 'NPHQ'",
      "Login-Fix: Admin-User (ADMIN_USER_IDS) können sich jetzt auch ohne Discord-Server-Mitgliedschaft einloggen",
      "Login-Fix: Discord OAuth fragt jetzt immer nach Berechtigung — behebt Scope-Probleme bei bestehenden Autorisierungen",
      "Piratensprache komplett auf Deutsch umgeschrieben mit Memes und Emojis",
    ],
  },
  {
    version: "1.8.0",
    date: "2026-04-09",
    tags: ["feature"],
    title: "Browser-Benachrichtigungen",
    changes: [
      "Desktop-Benachrichtigungen: Pop-ups bei neuen Trainings, Matches und Ankündigungen — auch wenn der Tab im Hintergrund ist",
      "Automatische Nachfrage beim ersten Besuch ob Browser-Benachrichtigungen aktiviert werden sollen",
      "Ein/Aus-Schalter in den Einstellungen unter Benachrichtigungen",
      "Benachrichtigungen werden nur angezeigt wenn der Tab nicht fokussiert ist",
      "Fix: Migrations nutzten falsche Spaltennamen (snake_case statt camelCase) — Deployment schlug fehl",
    ],
  },
  {
    version: "1.7.0",
    date: "2026-04-08",
    tags: ["feature"],
    title: "Mehrsprachigkeit (i18n): Deutsch, Englisch & Piratensprache",
    changes: [
      "Komplette i18n-Infrastruktur: React Context Provider, namespaced Translation-Keys, Fallback auf Deutsch",
      "3 Sprachen: Deutsch (Standard), Englisch, Piratensprache (Meme-Sprache)",
      "Sprachauswahl in persönlichen Einstellungen — wird im Profil und localStorage gespeichert",
      "Automatische Erkennung der Browser-Sprache für neue Nutzer",
      "Alle Seiten übersetzt: Dashboard, Training, Matches, Strategien, Lineup, Scouting, Umfragen, Ankündigungen, Wiki, Notizen, Erinnerungen, Verfügbarkeit, Replays, Einstellungen",
      "Navigation, Header, Benachrichtigungen und Login-Seite übersetzt",
      "HTML lang-Attribut wird dynamisch aktualisiert",
    ],
  },
  {
    version: "1.6.0",
    date: "2026-04-08",
    tags: ["feature"],
    title: "WhatsApp-Benachrichtigungen & Kanal-Auswahl",
    changes: [
      "Benachrichtigungs-Kanal in Einstellungen wählbar: E-Mail (SMTP), WhatsApp oder Aus",
      "WhatsApp-Integration: Trainings, Matches, Ankündigungen und Erinnerungen werden per WhatsApp verschickt",
      "Wenn SMTP- oder WhatsApp-Umgebungsvariablen nicht gesetzt sind, ist die jeweilige Option ausgegraut",
      "Discord-Webhooks funktionieren immer unabhängig vom gewählten Kanal",
      "Neues Telefon-Feld in persönlichen Einstellungen für WhatsApp-Nummer",
      "Alle bestehenden E-Mail-Benachrichtigungen (Trainings, Matches, Ankündigungen, Erinnerungen) laufen jetzt über den konfigurierten Kanal",
    ],
  },
  {
    version: "1.5.0",
    date: "2026-04-08",
    tags: ["feature", "breaking"],
    title: "Scrims in Matches zusammengeführt",
    changes: [
      "Scrims sind jetzt Teil von Matches — neuer Typ-Filter: Scrim, Turnier, Liga, Freundschaftlich, Sonstige",
      "Match-Erstellung mit Typ-Auswahl: je nach Typ werden passende Felder angezeigt (Map-Pool, Format, Kontakt etc.)",
      "Teilnahme-Abstimmung (Verfügbar/Nicht verfügbar/Vielleicht) direkt im Match für Scrim-Typ",
      "Ergebnis nachträglich eintragen für Scrims ohne initiale Scores inkl. Bewertungen",
      "Statistik-Leiste passt sich dem aktiven Typ-Filter an",
      "Bestehende Scrim-Daten wurden automatisch in Matches migriert (alle Links/Referenzen bleiben intakt)",
      "Scrims-Seite und Navigation entfernt — alles unter Matches",
    ],
  },
  {
    version: "1.4.0",
    date: "2026-04-08",
    tags: ["feature", "improvement"],
    title: "Sicherheit, Performance & Infrastruktur",
    changes: [
      "CSRF-Schutz: Double-Submit-Cookie-Pattern auf allen Mutation-Endpoints",
      "Rate-Limiting: 60 Requests/Minute auf POST/PUT/DELETE-Endpoints",
      "File-Upload-Validierung: Magic-Bytes-Check gegen manipulierte Dateien",
      "Strukturiertes Logging: Pino JSON-Logger mit Log-Levels statt console.log",
      "Graceful Shutdown: Server schließt DB-Verbindungen und Requests sauber bei SIGTERM",
      "Docker Health-Checks: Server und Client werden automatisch überwacht und neugestartet",
      "Datenbank-Indexes: 18 neue Indexes auf Foreign-Keys und Zeit-Queries für schnellere Abfragen",
      "In-Memory-Cache: Team-Config und Game-Config werden 60 Sekunden gecacht",
      "Pagination-Helper: Einheitliche Pagination für Listen-Endpoints",
      "Batch-Queries: Scheduler lädt Trainings/Matches in einem Query statt einzeln",
      "Parallele E-Mails: Benachrichtigungen werden mit Promise.all statt sequentiell versendet",
      "E-Mail-Benachrichtigungen: Neue Mails für Event-Änderungen, Löschungen, Announcements und Poll-Ergebnisse",
      "Socket.io Client-Hook: useSocket mit Singleton-Pattern und Ref-Counting",
      "Socket.io Safe-Emit: Fehlerbehandlung statt stille try/catch-Blöcke",
      "Playbooks-UI: Komplette Seite zum Erstellen, Bearbeiten und Verwalten von Playbooks",
      "Admin-Dashboard: Statistiken mit User-Aktivität, Entity-Counts und Speicherverbrauch",
      "Daten-Export: Match-Statistiken, Training-Teilnahme und Verfügbarkeit als CSV/JSON",
      "Error Boundary: React-Fehler crashen nicht mehr die ganze App",
      "PWA-Support: Manifest für 'Zum Startbildschirm hinzufügen' auf Mobilgeräten",
      "Tests: Vitest-Konfiguration mit Tests für CSRF, Rollen, Cache und File-Validierung",
    ],
  },
  {
    version: "1.3.0",
    date: "2026-04-08",
    tags: ["feature", "improvement"],
    title: "Toast-Benachrichtigungen, Notifications & UX-Verbesserungen",
    changes: [
      "Toast/Snackbar-System: Erfolgs- und Fehlermeldungen erscheinen als hübsche Benachrichtigungen statt inline-Text",
      "Toast-Notifications auf allen 16 Seiten integriert — keine stillen Fehler mehr",
      "Benachrichtigungs-Glocke im Header mit Ungelesen-Zähler und Dropdown",
      "Match-Review-Tab: Positives, Negatives, Verbesserungen und Notizen pro Match",
      "Training-Vorlagen: Trainings als Vorlage speichern und schnell laden",
      "Scouting-Notizen: Detaillierte Notizen pro Gegner mit Map-Zuordnung",
      "Dashboard-Aktivität: Lesbare Beschreibungen statt technischer Audit-Log-Daten",
      "Alle CS:GO-Referenzen entfernt — Maps und Seiten laden dynamisch aus R6 Siege Config",
      "Strats: Seiten von CT/T auf ATTACK/DEFENSE umgestellt (R6 Siege)",
      "Client-seitige Upload-Größen-Validierung (max. 50 MB)",
      "Alle 'as any' Type-Casts im Client entfernt — vollständig typsicher",
      "Produktions-Update-Script (update.sh) für Debian-Server mit DB-Backup, Health-Checks und Smoke-Tests",
    ],
  },
  {
    version: "1.2.0",
    date: "2026-04-08",
    tags: ["fix"],
    title: "Bugfix-Runde: Route-Mismatches & fehlende Endpunkte",
    changes: [
      "Dashboard-API hinzugefügt: Stats, nächste Events und Aktivität werden jetzt korrekt geladen",
      "Scouting: API-Routen und Datenmodell an Server angepasst (Opponent-Modell mit Bedrohungsstufen)",
      "Scrims-Ergebnis: HTTP-Methode korrigiert (PATCH → POST)",
      "Ankündigungen Pin/Bestätigen: HTTP-Methode korrigiert (PATCH → POST)",
      "Attendance-Abstimmung: Route korrigiert (/token/vote → /token)",
      "Verfügbarkeit: Tab-Buttons werden jetzt korrekt gestylt (primary statt ungültiges default)",
      "Lineup: Nicht-existierendes Aktivieren-Feature entfernt",
      "MOSS-Standalone-Seite leitet auf Matches weiter (MOSS ist jetzt pro Match)",
      "Server: Mitglied-Entfernen-Endpunkt hinzugefügt (DELETE /api/team/members)",
      "Server: Team-Logo-Upload-Endpunkt hinzugefügt (POST /api/team/logo)",
      "Letzte Umlaute korrigiert (Aktivitaet → Aktivität)",
    ],
  },
  {
    version: "1.1.0",
    date: "2026-04-08",
    tags: ["feature", "fix", "improvement"],
    title: "Match-Detail, externe Spieler & UI-Überarbeitung",
    changes: [
      "Match-Detail-Seite mit Spieler-Stats, MOSS-Uploads und Replays pro Match",
      "Externe/Aushilfsspieler können zu Matches hinzugefügt werden",
      "MOSS-Dateien werden pro Match und pro Spieler zugeordnet",
      "Replays sind jetzt direkt im Match verknüpft statt als eigener Bereich",
      "Training: Treffzeit (Pflicht), Beginn (Pflicht) und Ende (optional) hinzugefügt",
      "Scrims: Optionale Treffzeit hinzugefügt",
      "Match-Ergebnis wird automatisch aus den Scores berechnet (WIN/LOSS/DRAW)",
      "Maps werden aus der R6 Siege Game-Config geladen statt hardcoded",
      "Einstellungen nur noch für Admins sichtbar und zugänglich",
      "Sidebar zeigt Einstellungen nur für Admins",
      "MOSS und Replays aus der Navigation entfernt (jetzt unter Matches)",
      "Alle deutschen Texte verwenden echte Umlaute (ä, ö, ü) statt ae, oe, ue",
      "Changelog ist jetzt einklappbar, nur neueste Version aufgeklappt",
      "Fix: /api/teams → /api/team (404 nach Login behoben)",
      "Fix: /api/members → /api/team/members (Mitgliederliste war leer)",
      "Fix: Cookie secure-Flag basiert auf APP_URL statt NODE_ENV",
      "Fix: Root-Seite (/) leitet korrekt zum Dashboard weiter",
      "Fix: Favicon und Login-Logo zeigen die echten Team-Bilder",
      "Fix: Discord-Icon auf Login-Seite hat jetzt die Augen",
      "Fix: Admin-Zugriff nur noch über .env (ADMIN_USER_IDS/ADMIN_ROLE_IDS), nicht mehr erster User",
      "GitHub-Repository umgezogen nach NKr-NextDestiny/NextPhantomsHQ",
    ],
  },
  {
    version: "1.0.0",
    date: "2026-04-08",
    tags: ["feature"],
    title: "Umbenennung & Feature-Komplettpaket",
    changes: [
      "Projekt umbenannt von NextPhantoms zu Next Phantoms HQ",
      "Wiki für Team-Wissensdatenbank",
      "Persönliche und Team-Notizen mit Privat-Modus",
      "Erinnerungen und Deadlines mit Überfällig-Anzeige",
      "Verfügbarkeits-Heatmap für das ganze Team",
      "Training-Vorlagen für schnelles Erstellen",
      "Match-Reviews mit Positives/Negatives/Verbesserungen",
      "Globale Suche über alle Bereiche",
      "Discord-Webhooks für Match-, Training- und Scrim-Benachrichtigungen",
      "Benutzer-Dokumentation mit allen Features erklärt",
      "Changelog-Seite mit Versionsverlauf",
      "Alle Dependencies auf neueste stabile Versionen aktualisiert",
      "dev.bat: Automatischer Browser-Start, server/.env Auto-Erstellung",
      "clean.bat: Menü mit Optionen (nur Daten / alles / abbrechen)",
    ],
  },
  {
    version: "0.3.0",
    date: "2026-04-07",
    tags: ["feature", "fix"],
    title: "Lokale Entwicklung & DB-Fix",
    changes: [
      "server/.env für lokale Prisma-Migration mit localhost-URL",
      "prisma.config.ts liest DATABASE_URL manuell (Prisma 7 Kompatibilität)",
      "Fix: Server-Crash 'Can't reach database server at postgres' im lokalen Dev",
      "Fix: config/index.ts lädt server/.env vor root .env (localhost hat Priorität)",
    ],
  },
  {
    version: "0.2.0",
    date: "2026-04-07",
    tags: ["feature"],
    title: "R6 Siege Replay-Parser",
    changes: [
      "R6 Siege .rec Replay-Parser mit ZIP-Extraktion",
      "Kill-Erkennung und Runden-Statistiken aus Replay-Dateien",
      "Automatisches Parsen im Hintergrund nach Upload",
      "Spieler-Zuordnung per R6-Username",
      "ADMIN_USER_IDS für benutzerbasierte Admin-Zuweisung über Discord-ID",
    ],
  },
  {
    version: "0.1.0",
    date: "2026-04-06",
    tags: ["feature"],
    title: "Initial Release",
    changes: [
      "Discord OAuth Login mit Guild-Mitgliedschaft und Rollen-Prüfung",
      "Training-Verwaltung mit Abstimmungen und Erinnerungen",
      "Scrim-Management mit Ergebnissen und Bewertungen",
      "Match-Tracking mit Spieler-Statistiken",
      "Strategien-System mit Versionierung und Playbooks",
      "Lineup-Builder für Map/Side-Kombinationen",
      "Gegner-Scouting mit Bedrohungslevel und Notizen",
      "MOSS-Dateien Upload und Verwaltung",
      "Umfragen mit Mehrfachauswahl und Ablaufdatum",
      "Ankündigungen mit Pin-Funktion",
      "AES-256-GCM Dateiverschlüsselung für alle Uploads",
      "E-Mail-Benachrichtigungen via SMTP",
      "Echtzeit-Updates via Socket.io",
      "Responsive Dark-Theme mit Orange-Akzent",
      "JWT-Authentifizierung mit httpOnly Cookies",
      "PostgreSQL mit Prisma 7 ORM",
    ],
  },
];

