export interface ChangelogEntry {
  version: string;
  date: string;
  tags: ("feature" | "fix" | "improvement" | "breaking")[];
  title: string;
  changes: string[];
}

export const changelog: ChangelogEntry[] = [
  {
    version: "1.9.0",
    date: "2026-04-09",
    tags: ["feature", "improvement", "fix"],
    title: "Profil-Dropdown, Login-Fix & Piratensprache 2.0",
    changes: [
      "Persönliche Einstellungen (Name, E-Mail, Telefon, Sprache, Browser-Notifications) jetzt im Profil-Dropdown oben rechts — für alle Benutzer zugänglich",
      "Einstellungen-Seite ist jetzt rein Admin-only (kein persönlicher Tab mehr)",
      "Login-Fix: Admin-User (ADMIN_USER_IDS) können sich jetzt auch ohne Discord-Server-Mitgliedschaft einloggen",
      "Login-Fix: Discord OAuth fragt jetzt immer nach Berechtigung (prompt=consent statt prompt=none) — behebt Scope-Probleme bei bestehenden Autorisierungen",
      "Logging: Guild- und Rollen-Prüfung loggt jetzt Fehler mit Status-Codes für einfacheres Debugging",
      "Piratensprache komplett auf Deutsch umgeschrieben mit viel mehr Memes und Emojis 🏴‍☠️",
      "features.html komplett überarbeitet und auf Stand gebracht (Browser-Notifications, i18n, WhatsApp, Admin-Rechte, Profil-Dropdown, Tech Stack)",
    ],
  },
  {
    version: "1.8.0",
    date: "2026-04-09",
    tags: ["feature"],
    title: "Browser-Benachrichtigungen",
    changes: [
      "Desktop-Benachrichtigungen: Pop-ups bei neuen Trainings, Matches und Ankündigungen — auch wenn der Tab im Hintergrund ist",
      "Automatische Nachfrage beim ersten Besuch ob Browser-Benachrichtigungen aktiviert werden sollen",
      "Ein/Aus-Schalter in den Einstellungen unter Benachrichtigungen",
      "Benachrichtigungen werden nur angezeigt wenn der Tab nicht fokussiert ist",
      "Fix: Migrations nutzten falsche Spaltennamen (snake_case statt camelCase) — Deployment schlug fehl",
    ],
  },
  {
    version: "1.7.0",
    date: "2026-04-08",
    tags: ["feature"],
    title: "Mehrsprachigkeit (i18n): Deutsch, Englisch & Piratensprache",
    changes: [
      "Komplette i18n-Infrastruktur: React Context Provider, namespaced Translation-Keys, Fallback auf Deutsch",
      "3 Sprachen: Deutsch (Standard), Englisch, Piratensprache (Meme-Sprache)",
      "Sprachauswahl in persönlichen Einstellungen — wird im Profil und localStorage gespeichert",
      "Automatische Erkennung der Browser-Sprache für neue Nutzer",
      "Alle Seiten übersetzt: Dashboard, Training, Matches, Strategien, Lineup, Scouting, Umfragen, Ankündigungen, Wiki, Notizen, Erinnerungen, Verfügbarkeit, Replays, Einstellungen",
      "Navigation, Header, Benachrichtigungen und Login-Seite übersetzt",
      "HTML lang-Attribut wird dynamisch aktualisiert",
    ],
  },
  {
    version: "1.6.0",
    date: "2026-04-08",
    tags: ["feature"],
    title: "WhatsApp-Benachrichtigungen (WAHA) & Kanal-Auswahl",
    changes: [
      "Benachrichtigungs-Kanal in Einstellungen wählbar: E-Mail (SMTP), WhatsApp (WAHA) oder Aus",
      "WAHA-Integration: Trainings, Matches, Ankündigungen und Erinnerungen werden per WhatsApp verschickt",
      "Wenn SMTP- oder WAHA-Umgebungsvariablen nicht gesetzt sind, ist die jeweilige Option ausgegraut",
      "Discord-Webhooks funktionieren immer unabhängig vom gewählten Kanal",
      "Neues Telefon-Feld in persönlichen Einstellungen für WhatsApp-Nummer",
      "Alle bestehenden E-Mail-Benachrichtigungen (Trainings, Matches, Ankündigungen, Erinnerungen) laufen jetzt über den konfigurierten Kanal",
    ],
  },
  {
    version: "1.5.0",
    date: "2026-04-08",
    tags: ["feature", "breaking"],
    title: "Scrims in Matches zusammengeführt",
    changes: [
      "Scrims sind jetzt Teil von Matches — neuer Typ-Filter: Scrim, Turnier, Liga, Freundschaftlich, Sonstige",
      "Match-Erstellung mit Typ-Auswahl: je nach Typ werden passende Felder angezeigt (Map-Pool, Format, Kontakt etc.)",
      "Teilnahme-Abstimmung (Verfügbar/Nicht verfügbar/Vielleicht) direkt im Match für Scrim-Typ",
      "Ergebnis nachträglich eintragen für Scrims ohne initiale Scores inkl. Bewertungen",
      "Statistik-Leiste passt sich dem aktiven Typ-Filter an",
      "Bestehende Scrim-Daten wurden automatisch in Matches migriert (alle Links/Referenzen bleiben intakt)",
      "Scrims-Seite und Navigation entfernt — alles unter Matches",
    ],
  },
  {
    version: "1.4.0",
    date: "2026-04-08",
    tags: ["feature", "improvement"],
    title: "Sicherheit, Performance & Infrastruktur",
    changes: [
      "CSRF-Schutz: Double-Submit-Cookie-Pattern auf allen Mutation-Endpoints",
      "Rate-Limiting: 60 Requests/Minute auf POST/PUT/DELETE-Endpoints",
      "File-Upload-Validierung: Magic-Bytes-Check gegen manipulierte Dateien",
      "Strukturiertes Logging: Pino JSON-Logger mit Log-Levels statt console.log",
      "Graceful Shutdown: Server schließt DB-Verbindungen und Requests sauber bei SIGTERM",
      "Docker Health-Checks: Server und Client werden automatisch überwacht und neugestartet",
      "Datenbank-Indexes: 18 neue Indexes auf Foreign-Keys und Zeit-Queries für schnellere Abfragen",
      "In-Memory-Cache: Team-Config und Game-Config werden 60 Sekunden gecacht",
      "Pagination-Helper: Einheitliche Pagination für Listen-Endpoints",
      "Batch-Queries: Scheduler lädt Trainings/Matches in einem Query statt einzeln",
      "Parallele E-Mails: Benachrichtigungen werden mit Promise.all statt sequentiell versendet",
      "E-Mail-Benachrichtigungen: Neue Mails für Event-Änderungen, Löschungen, Announcements und Poll-Ergebnisse",
      "Socket.io Client-Hook: useSocket mit Singleton-Pattern und Ref-Counting",
      "Socket.io Safe-Emit: Fehlerbehandlung statt stille try/catch-Blöcke",
      "Playbooks-UI: Komplette Seite zum Erstellen, Bearbeiten und Verwalten von Playbooks",
      "Admin-Dashboard: Statistiken mit User-Aktivität, Entity-Counts und Speicherverbrauch",
      "Daten-Export: Match-Statistiken, Training-Teilnahme und Verfügbarkeit als CSV/JSON",
      "Error Boundary: React-Fehler crashen nicht mehr die ganze App",
      "PWA-Support: Manifest für 'Zum Startbildschirm hinzufügen' auf Mobilgeräten",
      "Tests: Vitest-Konfiguration mit Tests für CSRF, Rollen, Cache und File-Validierung",
    ],
  },
  {
    version: "1.3.0",
    date: "2026-04-08",
    tags: ["feature", "improvement"],
    title: "Toast-Benachrichtigungen, Notifications & UX-Verbesserungen",
    changes: [
      "Toast/Snackbar-System: Erfolgs- und Fehlermeldungen erscheinen als hübsche Benachrichtigungen statt inline-Text",
      "Toast-Notifications auf allen 16 Seiten integriert — keine stillen Fehler mehr",
      "Benachrichtigungs-Glocke im Header mit Ungelesen-Zähler und Dropdown",
      "Match-Review-Tab: Positives, Negatives, Verbesserungen und Notizen pro Match",
      "Training-Vorlagen: Trainings als Vorlage speichern und schnell laden",
      "Scouting-Notizen: Detaillierte Notizen pro Gegner mit Map-Zuordnung",
      "Dashboard-Aktivität: Lesbare Beschreibungen statt technischer Audit-Log-Daten",
      "Alle CS:GO-Referenzen entfernt — Maps und Seiten laden dynamisch aus R6 Siege Config",
      "Strats: Seiten von CT/T auf ATTACK/DEFENSE umgestellt (R6 Siege)",
      "Client-seitige Upload-Größen-Validierung (max. 50 MB)",
      "Alle 'as any' Type-Casts im Client entfernt — vollständig typsicher",
      "Produktions-Update-Script (update.sh) für Debian-Server mit DB-Backup, Health-Checks und Smoke-Tests",
    ],
  },
  {
    version: "1.2.0",
    date: "2026-04-08",
    tags: ["fix"],
    title: "Bugfix-Runde: Route-Mismatches & fehlende Endpunkte",
    changes: [
      "Dashboard-API hinzugefügt: Stats, nächste Events und Aktivität werden jetzt korrekt geladen",
      "Scouting: API-Routen und Datenmodell an Server angepasst (Opponent-Modell mit Bedrohungsstufen)",
      "Scrims-Ergebnis: HTTP-Methode korrigiert (PATCH → POST)",
      "Ankündigungen Pin/Bestätigen: HTTP-Methode korrigiert (PATCH → POST)",
      "Attendance-Abstimmung: Route korrigiert (/token/vote → /token)",
      "Verfügbarkeit: Tab-Buttons werden jetzt korrekt gestylt (primary statt ungültiges default)",
      "Lineup: Nicht-existierendes Aktivieren-Feature entfernt",
      "MOSS-Standalone-Seite leitet auf Matches weiter (MOSS ist jetzt pro Match)",
      "Server: Mitglied-Entfernen-Endpunkt hinzugefügt (DELETE /api/team/members)",
      "Server: Team-Logo-Upload-Endpunkt hinzugefügt (POST /api/team/logo)",
      "Letzte Umlaute korrigiert (Aktivitaet → Aktivität)",
    ],
  },
  {
    version: "1.1.0",
    date: "2026-04-08",
    tags: ["feature", "fix", "improvement"],
    title: "Match-Detail, externe Spieler & UI-Überarbeitung",
    changes: [
      "Match-Detail-Seite mit Spieler-Stats, MOSS-Uploads und Replays pro Match",
      "Externe/Aushilfsspieler können zu Matches hinzugefügt werden",
      "MOSS-Dateien werden pro Match und pro Spieler zugeordnet",
      "Replays sind jetzt direkt im Match verknüpft statt als eigener Bereich",
      "Training: Treffzeit (Pflicht), Beginn (Pflicht) und Ende (optional) hinzugefügt",
      "Scrims: Optionale Treffzeit hinzugefügt",
      "Match-Ergebnis wird automatisch aus den Scores berechnet (WIN/LOSS/DRAW)",
      "Maps werden aus der R6 Siege Game-Config geladen statt hardcoded",
      "Einstellungen nur noch für Admins sichtbar und zugänglich",
      "Sidebar zeigt Einstellungen nur für Admins",
      "MOSS und Replays aus der Navigation entfernt (jetzt unter Matches)",
      "Alle deutschen Texte verwenden echte Umlaute (ä, ö, ü) statt ae, oe, ue",
      "Changelog ist jetzt einklappbar, nur neueste Version aufgeklappt",
      "Fix: /api/teams → /api/team (404 nach Login behoben)",
      "Fix: /api/members → /api/team/members (Mitgliederliste war leer)",
      "Fix: Cookie secure-Flag basiert auf APP_URL statt NODE_ENV",
      "Fix: Root-Seite (/) leitet korrekt zum Dashboard weiter",
      "Fix: Favicon und Login-Logo zeigen die echten Team-Bilder",
      "Fix: Discord-Icon auf Login-Seite hat jetzt die Augen",
      "Fix: Admin-Zugriff nur noch über .env (ADMIN_USER_IDS/ADMIN_ROLE_IDS), nicht mehr erster User",
      "GitHub-Repository umgezogen nach NKr-NextDestiny/NextPhantomsHQ",
    ],
  },
  {
    version: "1.0.0",
    date: "2026-04-08",
    tags: ["feature"],
    title: "Umbenennung & Feature-Komplettpaket",
    changes: [
      "Projekt umbenannt von NextPhantoms zu Next Phantoms HQ",
      "Wiki für Team-Wissensdatenbank",
      "Persönliche und Team-Notizen mit Privat-Modus",
      "Erinnerungen und Deadlines mit Überfällig-Anzeige",
      "Verfügbarkeits-Heatmap für das ganze Team",
      "Training-Vorlagen für schnelles Erstellen",
      "Match-Reviews mit Positives/Negatives/Verbesserungen",
      "Globale Suche über alle Bereiche",
      "Discord-Webhooks für Match-, Training- und Scrim-Benachrichtigungen",
      "Benutzer-Dokumentation mit allen Features erklärt",
      "Changelog-Seite mit Versionsverlauf",
      "Alle Dependencies auf neueste stabile Versionen aktualisiert",
      "dev.bat: Automatischer Browser-Start, server/.env Auto-Erstellung",
      "clean.bat: Menü mit Optionen (nur Daten / alles / abbrechen)",
    ],
  },
  {
    version: "0.3.0",
    date: "2026-04-07",
    tags: ["feature", "fix"],
    title: "Lokale Entwicklung & DB-Fix",
    changes: [
      "server/.env für lokale Prisma-Migration mit localhost-URL",
      "prisma.config.ts liest DATABASE_URL manuell (Prisma 7 Kompatibilität)",
      "Fix: Server-Crash 'Can't reach database server at postgres' im lokalen Dev",
      "Fix: config/index.ts lädt server/.env vor root .env (localhost hat Priorität)",
    ],
  },
  {
    version: "0.2.0",
    date: "2026-04-07",
    tags: ["feature"],
    title: "R6 Siege Replay-Parser",
    changes: [
      "R6 Siege .rec Replay-Parser mit ZIP-Extraktion",
      "Kill-Erkennung und Runden-Statistiken aus Replay-Dateien",
      "Automatisches Parsen im Hintergrund nach Upload",
      "Spieler-Zuordnung per R6-Username",
      "ADMIN_USER_IDS für benutzerbasierte Admin-Zuweisung über Discord-ID",
    ],
  },
  {
    version: "0.1.0",
    date: "2026-04-06",
    tags: ["feature"],
    title: "Initial Release",
    changes: [
      "Discord OAuth Login mit Guild-Mitgliedschaft und Rollen-Prüfung",
      "Training-Verwaltung mit Abstimmungen und Erinnerungen",
      "Scrim-Management mit Ergebnissen und Bewertungen",
      "Match-Tracking mit Spieler-Statistiken",
      "Strategien-System mit Versionierung und Playbooks",
      "Lineup-Builder für Map/Side-Kombinationen",
      "Gegner-Scouting mit Bedrohungslevel und Notizen",
      "MOSS-Dateien Upload und Verwaltung",
      "Umfragen mit Mehrfachauswahl und Ablaufdatum",
      "Ankündigungen mit Pin-Funktion",
      "AES-256-GCM Dateiverschlüsselung für alle Uploads",
      "E-Mail-Benachrichtigungen via SMTP",
      "Echtzeit-Updates via Socket.io",
      "Responsive Dark-Theme mit Orange-Akzent",
      "JWT-Authentifizierung mit httpOnly Cookies",
      "PostgreSQL mit Prisma 7 ORM",
    ],
  },
];
